<?php
/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class QuestionnaireMetadata {

  static $swaggerTypes = array(
      'assigned_questions' => 'int',
      'guid' => 'string',
      'id' => 'float',
      'expires' => 'int',
      'status' => 'string',
      'name' => 'string',
      'descr' => 'string',
      'modified' => 'int',
      'total_questions' => 'int'

    );

  public $assigned_questions; // int
  public $guid; // string
  public $id; // float
  public $expires; // int
  public $status; // string
  public $name; // string
  public $descr; // string
  public $modified; // int
  public $total_questions; // int
  }

