<?php
/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class SignatureFieldInfo {

  static $swaggerTypes = array(
      'fontName' => 'string',
      'fontColor' => 'string',
      'regularExpression' => 'string',
      'fieldType' => 'int',
      'graphSizeH' => 'int',
      'fontBold' => 'bool',
      'fontSize' => 'float',
      'isSystem' => 'bool',
      'id' => 'string',
      'acceptableValues' => 'string',
      'fontItalic' => 'bool',
      'fontUnderline' => 'bool',
      'name' => 'string',
      'getDataFrom' => 'string',
      'defaultValue' => 'string',
      'graphSizeW' => 'int'

    );

  public $fontName; // string
  public $fontColor; // string
  public $regularExpression; // string
  public $fieldType; // int
  public $graphSizeH; // int
  public $fontBold; // bool
  public $fontSize; // float
  public $isSystem; // bool
  public $id; // string
  public $acceptableValues; // string
  public $fontItalic; // bool
  public $fontUnderline; // bool
  public $name; // string
  public $getDataFrom; // string
  public $defaultValue; // string
  public $graphSizeW; // int
  }

