<?php
/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class SignatureEnvelopeFieldInfo {

  static $swaggerTypes = array(
      'regularExpression' => 'string',
      'fieldType' => 'int',
      'mandatory' => 'bool',
      'data' => 'array[int]',
      'id' => 'string',
      'acceptableValues' => 'string',
      'recipientId' => 'string',
      'order' => 'float',
      'signatureFieldId' => 'float',
      'locations' => 'array[SignatureEnvelopeFieldLocationInfo]',
      'envelopeId' => 'string',
      'name' => 'string',
      'fillTimeStamp' => 'string',
      'getDataFrom' => 'string',
      'defaultValue' => 'string',
      'tooltip' => 'string'

    );

  public $regularExpression; // string
  public $fieldType; // int
  public $mandatory; // bool
  public $data; // array[int]
  public $id; // string
  public $acceptableValues; // string
  public $recipientId; // string
  public $order; // float
  public $signatureFieldId; // float
  public $locations; // array[SignatureEnvelopeFieldLocationInfo]
  public $envelopeId; // string
  public $name; // string
  public $fillTimeStamp; // string
  public $getDataFrom; // string
  public $defaultValue; // string
  public $tooltip; // string
  }

