<?php
/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class AnnotationInfo {

  static $swaggerTypes = array(
      'createdOn' => 'string',
      'guid' => 'string',
      'sessionGuid' => 'string',
      'documentGuid' => 'string',
      'annotationPosition' => 'Point',
      'range' => 'Range',
      'creatorGuid' => 'string',
      'svgPath' => 'string',
      'replies' => 'array[AnnotationReplyInfo]',
      'box' => 'Rectangle',
      'access' => 'string',
      'type' => 'string'

    );

  public $createdOn; // string
  public $guid; // string
  public $sessionGuid; // string
  public $documentGuid; // string
  public $annotationPosition; // Point
  public $range; // Range
  public $creatorGuid; // string
  public $svgPath; // string
  public $replies; // array[AnnotationReplyInfo]
  public $box; // Rectangle
  public $access; // string
  public $type; // string
  }

