<?php
/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class BillingAddressInfo {

  static $swaggerTypes = array(
      'zip' => 'string',
      'lastName' => 'string',
      'phone' => 'string',
      'fax' => 'string',
      'email' => 'string',
      'company' => 'string',
      'state' => 'string',
      'address1' => 'string',
      'address2' => 'string',
      'firstName' => 'string',
      'country' => 'string',
      'city' => 'string'

    );

  public $zip; // string
  public $lastName; // string
  public $phone; // string
  public $fax; // string
  public $email; // string
  public $company; // string
  public $state; // string
  public $address1; // string
  public $address2; // string
  public $firstName; // string
  public $country; // string
  public $city; // string
  }

