<?php
/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class ViewDocumentResult {

  static $swaggerTypes = array(
      'guid' => 'string',
      'id' => 'float',
      'page_size' => 'Dimension',
      'token' => 'string',
      'name' => 'string',
      'image_urls' => 'array[string]',
      'doc_type' => 'string',
      'url' => 'string',
      'page_count' => 'int',
      'version' => 'int'

    );

  public $guid; // string
  public $id; // float
  public $page_size; // Dimension
  public $token; // string
  public $name; // string
  public $image_urls; // array[string]
  public $doc_type; // string
  public $url; // string
  public $page_count; // int
  public $version; // int
  }

